spring:
  profiles:
   active:
    -dev
---
server:
 port: 8202
spring:
  profiles: dev
  application:
   name: config-dev
eureka:
   client: #客户端注册进eureka服务列表内
     service-url:
       defaultZone: http://localhost:7001/eureka
---
server:
  port: 8201
spring:
  profiles: test
  application:
   name: config-test
eureka:
    client: #客户端注册进eureka服务列表内
      service-url:
        defaultZone: http://localhost:7001/eureka